# Generated by Django 5.0.6 on 2024-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
